name: Docker Build and Push

on:
  push:
    branches:
      - docker_practise

env:
  IMAGE_NAME: studio

jobs:
  build-and-push:
    name: Build And Push Images
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download source code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push image to Docker Hub
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest